version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Lisbon
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
